In [2]:
import httpx

In [3]:
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/despesaDetalhada?elementosPorPagina=40471&pagina=1&termoBase64=&indAgrupamento=FOR&datInicio=2017-01-01&datFim=2026-07-31&desNatureza=&codAdministracao=1&filtrarApenasCovid=false&numEmpenho='

In [4]:
response = httpx.get(url)

with open("output.json", 'w', encoding = 'utf-8') as file: file.write(response.text)

In [5]:
import json
data = json.loads(response.text)

In [6]:
keys = data['content'][0].keys()
keys

dict_keys(['codDespesaDetalhada', 'nomFornecedor', 'desDocumentoFornecedor', 'numEmpenho', 'numAnoEmpenho', 'vlrEmpenhado', 'vlrLiquidado', 'vlrPago', 'datMovimento', 'datVencimento', 'codOrgao', 'desOrgao', 'codUnidade', 'desUnidade', 'codFuncao', 'desFuncao', 'codSubFuncao', 'desSubFuncao', 'desFonte', 'vlrLiquidoPago', 'desHistoricoLiquido', 'desEmpenhoHistorico', 'codAdministracao', 'desAdministracao', 'codPrograma', 'desPrograma', 'codAcao', 'desAcao', 'desModalidade', 'desLicitacaoEmpenho', 'desProcessoEmpenho', 'desContratoEmpenho', 'desDespesa', 'desDespesaOrcamentaria', 'desServico', 'desClassificacao', 'numLiquidacao', 'numPagamento', 'indCovid', 'numNotaFiscal', 'vlrDescontoInss', 'vlrDescontoIrrf', 'vlrDescontoIss', 'vlrDescontoOutros', 'desAgrupamento', 'datLiquidacao', 'datPagamento', 'datUltimoMovimento', 'licitacaoOutraAdministracao', 'codAdministracaoLicitacaoEmpenho', 'descricao', 'titulo', 'rota', 'chave', 'mostrarLicitacao', 'vlrMovimento', 'totalDesconto', 'desMovimento', 'fornecedorFormatado', 'empenhoFormatado', 'desLicitacaoEmpenhoFormatado', 'vlrEmpenhadoFormatado', 'vlrLiquidadoFormatado', 'desDocumentoFornecedorFormatado', 'desDepesaNaturezaFormatado', 'vlrPagoFormatado'])

In [8]:
extractedData = [list(keys)]

for i in range(len(data['content'])):
    tempList = []
    for k in keys:
        tempList.append(data['content'][i][k])
    extractedData.append(tempList)

In [10]:
import csv

with open ('allData.csv', 'w', newline="", encoding='utf-8') as file:
    writer = csv.writer(file, delimiter=';')
    writer.writerows(extractedData)

In [ ]:
# Despesa orçamentária

# Pesquisar despesas:
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/despesaDetalhada?elementosPorPagina=20&pagina=1&termoBase64=&indAgrupamento=FOR&datInicio=2026-07-01&datFim=2026-07-23&desNatureza=&codAdministracao=1&filtrarApenasCovid=false&numEmpenho='

# Busca por Fornecedor
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/despesaDetalhada?elementosPorPagina=20&pagina=1&termoBase64=NjIuMTcwLjI4Ni8wMDAxLTAw&indAgrupamento=FOR&datInicio=2026-07-01&datFim=2026-07-31&desNatureza=&codAdministracao=1&filtrarApenasCovid=false&numEmpenho='

# Visualizar detalhes da despesa:
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/despesaDetalhada/buscarMovimentacao?numEmpenho=004127&numAnoEmpenho=2026&codAdministracao=1'

# Detalhes da licitação / Empenho | Numero e anos vem nos detalhes da despesa
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/licitacao/buscarResultadoPesquisa?numLicitacao=000009&numAnoLicitacao=2025&codAdministracao=1&numProcesso=000090'

# Descontos do empenho
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/despesaDetalhada/buscarDescontosEmpenho?numEmpenho=003428&numAnoEmpenho=2026&codAdministracao=1'

# Dados do Contrato | Numero e anos vem nos detalhes da despesa
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/contrato/buscarResultadoPesquisa?numContrato=0000000000000000068&numAnoContrato=2026&codAdministracao=1'


# Informações do contrato | Codigo do contrato está nos dados do contrato
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/contrato/648'

# Obter documentos armazenados | O numero do documento está nas Informações do contrato
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/contrato/downloadArquivoBanco/2164'

# Detalhar licitação
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/licitacao/buscarResultadoPesquisa?numLicitacao=000009&numAnoLicitacao=2025&codAdministracao=1&numProcesso=000090'

# Informações da licitação | Numero está nos detalhes da licitação
url = 'https://transparencia.lagoaformosa.mg.gov.br/publico/licitacao/503'

In [15]:
import pandas as pd

df = pd.DataFrame(extractedData[1:], columns=extractedData[0])
df

,desAgrupamento,nomFornecedor,desDocumentoFornecedor,numEmpenho,numAnoEmpenho,vlrEmpenhado,vlrLiquidado,vlrPago,datMovimento,datVencimento,desModalidade
0,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,None,59.371.293/0001-66,004127,2026,180.00,0.00,0.00,None,None,Dispensada
1,03.574.171/0001-12 - MANG PATOS LTDA,None,03.574.171/0001-12,004126,2026,96.00,0.00,0.00,None,None,Dispensada
2,66.717.719/0001-56 - PATOS HIDRAULICA LTDA,None,66.717.719/0001-56,004125,2026,1800.00,0.00,0.00,None,None,Dispensada
3,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,None,59.371.293/0001-66,004124,2026,100.00,0.00,0.00,None,None,Dispensada
4,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,None,59.371.293/0001-66,004123,2026,180.00,0.00,0.00,None,None,Dispensada
...,...,...,...,...,...,...,...,...,...,...,...
40466,***.320.576-** - MARCELO DOMINGUES VIEIRA,None,034.320.576-95,000005,2021,189.00,189.00,189.00,None,None,Dispensada
40467,***.271.246-** - LAURO RIBEIRO DE MENDONÇA,None,038.271.246-38,000004,2021,94.50,94.50,94.50,None,None,Dispensada
40468,***.619.266-** - SEBASTIAO ANSELMO GOMES DOS S...,None,008.619.266-33,000003,2021,68.72,68.72,68.72,None,None,Dispensada
40469,***.872.446-** - ADAN CARLOS REZENDE RIBEIRO,None,091.872.446-59,000002,2021,94.50,94.50,94.50,None,None,Dispensada
40470,***.444.296-** - ONIVAL BERNARDES DA COSTA,None,578.444.296-15,000001,2021,94.50,94.50,94.50,None,None,Dispensada

In [24]:
# df['nomFornecedor','datMovimento','datVencimento' ] = df['nomFornecedor','datMovimento','datVencimento' ].astype(str)
for i in ['nomFornecedor','datMovimento','datVencimento' ]:
    df[i] = df[i].astype(str)

In [26]:
df2 = df.dropna()

In [29]:
df

,desAgrupamento,nomFornecedor,desDocumentoFornecedor,numEmpenho,numAnoEmpenho,vlrEmpenhado,vlrLiquidado,vlrPago,datMovimento,datVencimento,desModalidade
0,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,NaN,59.371.293/0001-66,004127,2026,180.00,0.00,0.00,NaN,NaN,Dispensada
1,03.574.171/0001-12 - MANG PATOS LTDA,NaN,03.574.171/0001-12,004126,2026,96.00,0.00,0.00,NaN,NaN,Dispensada
2,66.717.719/0001-56 - PATOS HIDRAULICA LTDA,NaN,66.717.719/0001-56,004125,2026,1800.00,0.00,0.00,NaN,NaN,Dispensada
3,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,NaN,59.371.293/0001-66,004124,2026,100.00,0.00,0.00,NaN,NaN,Dispensada
4,59.371.293/0001-66 - 59 371 293 MAX BRAGA DA S...,NaN,59.371.293/0001-66,004123,2026,180.00,0.00,0.00,NaN,NaN,Dispensada
...,...,...,...,...,...,...,...,...,...,...,...
40466,***.320.576-** - MARCELO DOMINGUES VIEIRA,NaN,034.320.576-95,000005,2021,189.00,189.00,189.00,NaN,NaN,Dispensada
40467,***.271.246-** - LAURO RIBEIRO DE MENDONÇA,NaN,038.271.246-38,000004,2021,94.50,94.50,94.50,NaN,NaN,Dispensada
40468,***.619.266-** - SEBASTIAO ANSELMO GOMES DOS S...,NaN,008.619.266-33,000003,2021,68.72,68.72,68.72,NaN,NaN,Dispensada
40469,***.872.446-** - ADAN CARLOS REZENDE RIBEIRO,NaN,091.872.446-59,000002,2021,94.50,94.50,94.50,NaN,NaN,Dispensada
40470,***.444.296-** - ONIVAL BERNARDES DA COSTA,NaN,578.444.296-15,000001,2021,94.50,94.50,94.50,NaN,NaN,Dispensada

In [31]:
import pantab

pantab.frame_to_hyper(df, "lagoa2.hyper", table="Lagoa")